### ISSUE TITLE
Add darwin_arm64 binaries on Terraform registry

### ISSUE THREAD

**Issue by jbg** [ekristen/terraform-provider-pgp#14]
I don't have much experience with Go but my understanding is that this should be quite straightforward due to Go's easy cross-compiling.

```
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/ekristen/pgp v0.2.1 does not have a package available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
╵
```

**Comment by ekristen** [comment]
@jbg odd, it should be there. unsure why it is not. I'll take a look.

**Comment by ekristen** [comment]
https://github.com/ekristen/terraform-provider-pgp/releases/tag/v0.2.4 should fix it, the darwin_amd64 binary is now there.
