### ISSUE TITLE
Release an updated version?

### ISSUE THREAD

**Issue by jbg** [ekristen/terraform-provider-pgp#3]
I came here to look at submitting an issue/PR for supporting base64-encoded ciphertext in the `pgp_decrypt` resource, but I now see that it's already implemented – would it be possible to release the updated version?

**Comment by jbg** [comment]
On digging deeper I now see that the released version 0.2.0 does in fact support base64-encoded ciphertext, but the `ciphertext_encoding` attribute is not mentioned in the [documentation](https://registry.terraform.io/providers/ekristen/pgp/latest/docs/data-sources/pgp_decrypt).

**Comment by ekristen** [comment]
I've updated the documentation and published 0.2.1.
